// angular/src/app/app.component.ts
import { Component } from "@angular/core";

type Movie = {
  name: string;
  available: number;
  quantity: number;
};

type Movies = Array<Movie>;

@Component({
  selector: "app-root",
  template: ` <h2>Peliculas</h2> `,
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title: string = "Peliculas";
  movies: Movies = [
    {
      name: "avengers",
      available: 3,
      quantity: 0
    },
    {
      name: "Terminator",
      available: 5,
      quantity: 0
    }
  ];

  addMovieQuantity(movieName) {
    const movieIndex = this.movies.findIndex(
      (movie) => movie.name === movieName
    );

    this.movies[movieIndex].quantity += 1;
  }
  removeMovieQuantity(movieName) {
    const movieIndex = this.movies.findIndex(
      (movie) => movie.name === movieName
    );

    this.movies[movieIndex].quantity -= 1;
  }
}

<h2>{{ title}}</h2>

<form *ngFor="let movie of movies">
  <h3>{{movie.name}}</h3>

  <button
    type="button"
    (click)="removeMovieQuantity(movie.name)"
    [disabled]="movie.quantity<=0"
  >
    -
  </button>
  {{movie.quantity}}
  <button
    type="button"
    (click)="addMovieQuantity(movie.name)"
    [disabled]="movie.quantity>=movie.available"
  >
    +
  </button>
</form>

// react/src/App.js
import React from "react";
import Form from "./form";
import { Title } from "./Title";
import { Theme } from "./Theme";

const movies = [
  {
    name: "Avengers",
    available: 5
  },
  {
    name: "Terminator",
    available: 3
  }
];

export default function App() {
  return (
    <Theme>
      <Title>Peliculas</Title>
      {movies.map((movie) => (
        <Form movie={movie} />
      ))}
    </Theme>
  );
}
