// svelte/Form.svelte
<script>
  import { form, button } from "./styles.js";

  const movies = [
    {
      name: "Avengers",
      quantity: 0,
      available: 3
    },
    {
      name: "Terminator",
      quantity: 0,
      available: 5
    }
  ];
</script>

{#each movies as movie}
  <form class="{form}">
    <h3>{movie.name}</h3>
    <button type="button" on:click={() => movie.quantity -= 1} disabled={movie.quantity <= 0} class="{button}">-</button>
    {movie.quantity}
    <button type="button" on:click={() => movie.quantity += 1} disabled={movie.quantity >= movie.available} class="{button}">+</button>
  </form>
{/each}

<style>
  /* form {
                background: var(--bg);
                color: var(--color2);
                border: 1px solid var(--color);
                font-family: "Courier New", Courier, monospace;
                margin: 0 50px 25px;
                padding: 10px 25px 25px;
                text-align: center;
                transform: scale(1);
                transition: transform 0.3s;
              }
              form:hover {
                transform: scale(1.2);
              } */

  button {
  }
  button:hover {
  }
  button[disabled] {
  }
</style>

// react/src/form.js
import React from "react";
import styled from "styled-components";

const StyledForm = styled.form`
  font-family: "Courier New", Courier, monospace;
  margin: 0 50px 25px;
  padding: 10px 25px 25px;
  text-align: center;
  transform: scale(1);
  transition: transform 0.3s;

  &:hover {
    transform: scale(1.2);
  }
`;

const StyledButton = styled.button`
  cursor: pointer;
  padding: 5px 10px;
  border: 1px solid transparent;
  transition: border-color 0.15s;

  &:hover {
    border-color: ${(p) => p.theme.color2};
  }

  &[disabled] {
    background: ${(p) => p.theme.color2};
  }
`;

export default function Form(props) {
  const [quantity, setQuantity] = React.useState(0);
  const { movie } = props;
  return (
    <StyledForm>
      <h3>{movie.name}</h3>
      <StyledButton
        type="button"
        onClick={() => setQuantity(quantity - 1)}
        disabled={quantity <= 0}
      >
        -
      </StyledButton>
      {quantity}
      <StyledButton
        type="button"
        onClick={() => setQuantity(quantity + 1)}
        disabled={quantity >= movie.available}
      >
        +
      </StyledButton>
    </StyledForm>
  );
}
