// vue3/src/App.vue
<template>
  <h2>Peliculas</h2>
  <Form />
</template>

<script>
import Form from "./components/Form.vue";
export default {
  name: "App",
  components: {
    Form: Form,
  },
};
</script>

<style lang="scss">
@import "./styles/_variables.scss";

html,
body {
  background: $bg;
  color: $color;
  margin: 0;
  font-family: sans-serif;
}

h2 {
  border-bottom: 1px solid $color;
  padding: 10px;
}
</style>

// svelte/App.svelte
<script>
  import Form from "./Form.svelte";
  import { title } from "./styles.js";
</script>

<main>
	<h2 class="{title}">Peliculas</h2>
  
  <Form />
</main>

<style>
  :global(body) {
    --bg: #ffe9c5;
    --color: #e54b00;
    --color2: #512613;
    background: var(--bg);
    color: var(--color);
    margin: 0;
    font-family: sans-serif;
  }
</style>
